apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: assign1
type: Opaque
data:
  api-key: bXlhcGlrZXk=        # base64 of "myapikey"
  db-password: bXlwYXNzd29yZA== # base64 of "mypassword"