apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-config
  namespace: assign1
  labels:
    app: backend
data:
  PODINFO_UI_MESSAGE: "Hello from ConfigMap - Assignment 1"
  PODINFO_UI_COLOR: "#34577c"
  PODINFO_CACHE_SERVER: "tcp://redis:6379"    # ← Cache address yahan