kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-cluster
nodes:
- role: control-plane
  # Ingress ke liye port mapping zaroori hai
  # HOST machine ka port → KIND container ka port
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80    # KIND container ka port 80
    hostPort: 80         # Host machine par bhi port 80
    protocol: TCP
  - containerPort: 443   # KIND container ka port 443
    hostPort: 443        # Host machine par bhi port 443
    protocol: TCP
