  kind: ConfigMap
  metadata:
    name: nginx-config       # ← YEH NAAM yaad rakhein!
    namespace: assign1
  data:
    nginx.conf: |            # ← KEY ka naam "nginx.conf" hai
      server {
        listen 80;
        location /api/ { proxy_pass http://backend:9898/; }
        location /whoami/ { proxy_pass http://whoami:80/; }
        location / { root /usr/share/nginx/html; }
      }
# Formula sirf 2 cheezein hain:
  
#   http://<Service ka name>:<Service ka port>/
  
#   Bas itna! Aur dono cheezein tumhari Service YAML file mein hoti hain.

 
  # backend_service.yaml
  # metadata:
  #   name: backend        ← YE NAAM liya  →  http://backend:????/
  # spec:
  #   ports:
  #   - port: 9898         ← YE PORT liya  →  http://backend:9898/