apiVersion: v1
kind: ConfigMap
metadata:
  name: static-content
  namespace: assign1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Welcome</title></head>
    <body>
      <h1>Hello from Nginx Static Page!</h1>
      <p>API Key: (injected via secret)</p>
    </body>
    </html>