apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":null,"name":"assign1"}}
  creationTimestamp: "2026-10-02T05:38:12Z"
  labels:
    kubernetes.io/metadata.name: assign1
  name: assign1
  resourceVersion: "926"
  uid: 67e0074f-2822-405d-82f9-51870afe612b
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
